import { Product, Transaction } from './types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Roti Tawar',
    price: 15000,
    category: 'Roti',
    stock: 25,
    imageUrl: '/images/roti-tawar.png',
  },
  {
    id: '2',
    name: 'Croissant Butter',
    price: 8000,
    category: 'Pastry',
    stock: 18,
    imageUrl: '/images/croissant.png',
  },
  {
    id: '3',
    name: 'Donat Coklat',
    price: 5000,
    category: 'Donat',
    stock: 32,
    imageUrl: '/images/donat.png',
  },
  {
    id: '4',
    name: 'Brownie Fudge',
    price: 12000,
    category: 'Kue',
    stock: 15,
    imageUrl: '/images/brownie.png',
  },
  {
    id: '5',
    name: 'Muffin Blueberry',
    price: 6500,
    category: 'Kue',
    stock: 20,
    imageUrl: '/images/muffin.png',
  },
  {
    id: '6',
    name: 'Baguette Perancis',
    price: 18000,
    category: 'Roti',
    stock: 12,
    imageUrl: '/images/baguette.png',
  },
  {
    id: '7',
    name: 'Tart Strawberry',
    price: 25000,
    category: 'Kue',
    stock: 8,
    imageUrl: '/images/tart.png',
  },
  {
    id: '8',
    name: 'Roti Sobek',
    price: 10000,
    category: 'Roti',
    stock: 22,
    imageUrl: '/images/sobek.png',
  },
  {
    id: '9',
    name: 'Pain au Chocolat',
    price: 7500,
    category: 'Pastry',
    stock: 19,
    imageUrl: '/images/pain.png',
  },
  {
    id: '10',
    name: 'Kue Lapis Legit',
    price: 35000,
    category: 'Kue',
    stock: 5,
    imageUrl: '/images/legit.png',
  },
  {
    id: '11',
    name: 'Roti Cane',
    price: 6000,
    category: 'Roti',
    stock: 28,
    imageUrl: '/images/cane.png',
  },
  {
    id: '12',
    name: 'Cheese Cake',
    price: 22000,
    category: 'Kue',
    stock: 10,
    imageUrl: '/images/cheesecake.png',
  },
];

export const CATEGORIES = ['Roti', 'Kue', 'Pastry', 'Minuman', 'Lainnya'];

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: 'TRX001',
    date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    items: [
      { product: MOCK_PRODUCTS[0], quantity: 2 },
      { product: MOCK_PRODUCTS[2], quantity: 3 },
    ],
    total: 45000,
    paymentMethod: 'tunai',
    kasirId: 'kasir1',
  },
  {
    id: 'TRX002',
    date: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    items: [{ product: MOCK_PRODUCTS[3], quantity: 1 }],
    total: 12000,
    paymentMethod: 'debit',
    kasirId: 'kasir1',
  },
  {
    id: 'TRX003',
    date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    items: [
      { product: MOCK_PRODUCTS[1], quantity: 2 },
      { product: MOCK_PRODUCTS[4], quantity: 1 },
    ],
    total: 19500,
    paymentMethod: 'qris',
    kasirId: 'kasir1',
  },
  {
    id: 'TRX004',
    date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    items: [{ product: MOCK_PRODUCTS[5], quantity: 1 }],
    total: 18000,
    paymentMethod: 'tunai',
    kasirId: 'kasir1',
  },
  {
    id: 'TRX005',
    date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    items: [
      { product: MOCK_PRODUCTS[6], quantity: 1 },
      { product: MOCK_PRODUCTS[4], quantity: 2 },
    ],
    total: 38000,
    paymentMethod: 'debit',
    kasirId: 'kasir1',
  },
  {
    id: 'TRX006',
    date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    items: [
      { product: MOCK_PRODUCTS[0], quantity: 1 },
      { product: MOCK_PRODUCTS[3], quantity: 1 },
    ],
    total: 27000,
    paymentMethod: 'qris',
    kasirId: 'kasir1',
  },
  {
    id: 'TRX007',
    date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    items: [
      { product: MOCK_PRODUCTS[2], quantity: 5 },
      { product: MOCK_PRODUCTS[8], quantity: 2 },
    ],
    total: 40000,
    paymentMethod: 'tunai',
    kasirId: 'kasir1',
  },
  {
    id: 'TRX008',
    date: new Date().toISOString(),
    items: [{ product: MOCK_PRODUCTS[11], quantity: 1 }],
    total: 22000,
    paymentMethod: 'debit',
    kasirId: 'kasir1',
  },
];
