import { Product, Transaction } from './types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'rb-coklat',
    name: 'Roti Bantal Coklat',
    price: 6000,
    category: 'Roti Bantal',
    stock: 50,
    imageUrl: '/images/roti-tawar.png',
  },
  {
    id: 'rb-keju',
    name: 'Roti Bantal Stik Keju',
    price: 6000,
    category: 'Roti Bantal',
    stock: 50,
    imageUrl: '/images/roti-tawar.png',
  },
  {
    id: 'rb-strawberry',
    name: 'Roti Bantal Strawberry',
    price: 6000,
    category: 'Roti Bantal',
    stock: 45,
    imageUrl: '/images/roti-tawar.png',
  },
  {
    id: 'rb-blueberry',
    name: 'Roti Bantal Blueberry',
    price: 6000,
    category: 'Roti Bantal',
    stock: 45,
    imageUrl: '/images/roti-tawar.png',
  },
  {
    id: 'rb-srikaya',
    name: 'Roti Bantal Srikaya',
    price: 6000,
    category: 'Roti Bantal',
    stock: 40,
    imageUrl: '/images/roti-tawar.png',
  },
  {
    id: 'rb-kelapa',
    name: 'Roti Bantal Kelapa',
    price: 6000,
    category: 'Roti Bantal',
    stock: 40,
    imageUrl: '/images/roti-tawar.png',
  },
  {
    id: 'rk-coklat',
    name: 'Roti Kecil Coklat',
    price: 3000,
    category: 'Roti Kecil',
    stock: 100,
    imageUrl: '/images/roti-tawar.png',
  },
  {
    id: 'rk-blueberry',
    name: 'Roti Kecil Blueberry',
    price: 3000,
    category: 'Roti Kecil',
    stock: 100,
    imageUrl: '/images/roti-tawar.png',
  },
  {
    id: 'rk-strawberry',
    name: 'Roti Kecil Strawberry',
    price: 3000,
    category: 'Roti Kecil',
    stock: 95,
    imageUrl: '/images/roti-tawar.png',
  },
  {
    id: 'rk-keju',
    name: 'Roti Kecil Keju',
    price: 3000,
    category: 'Roti Kecil',
    stock: 90,
    imageUrl: '/images/roti-tawar.png',
  },
  {
    id: 'rk-srikaya',
    name: 'Roti Kecil Srikaya',
    price: 3000,
    category: 'Roti Kecil',
    stock: 85,
    imageUrl: '/images/roti-tawar.png',
  },
  {
    id: 'rk-kelapa',
    name: 'Roti Kecil Kelapa',
    price: 3000,
    category: 'Roti Kecil',
    stock: 85,
    imageUrl: '/images/roti-tawar.png',
  },
];

export const CATEGORIES = ['Roti Bantal', 'Roti Kecil'];

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: 'TRX001',
    date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    items: [
      { product: MOCK_PRODUCTS[0], quantity: 2 },
      { product: MOCK_PRODUCTS[6], quantity: 3 },
    ],
    total: 21000,
    paymentMethod: 'tunai',
    kasirId: 'kasir1',
  },
  {
    id: 'TRX002',
    date: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    items: [{ product: MOCK_PRODUCTS[1], quantity: 1 }],
    total: 6000,
    paymentMethod: 'debit',
    kasirId: 'kasir1',
  },
  {
    id: 'TRX003',
    date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    items: [
      { product: MOCK_PRODUCTS[7], quantity: 2 },
      { product: MOCK_PRODUCTS[8], quantity: 1 },
    ],
    total: 9000,
    paymentMethod: 'qris',
    kasirId: 'kasir1',
  },
  {
    id: 'TRX004',
    date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    items: [{ product: MOCK_PRODUCTS[2], quantity: 1 }],
    total: 6000,
    paymentMethod: 'tunai',
    kasirId: 'kasir1',
  },
  {
    id: 'TRX005',
    date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    items: [
      { product: MOCK_PRODUCTS[3], quantity: 1 },
      { product: MOCK_PRODUCTS[9], quantity: 2 },
    ],
    total: 12000,
    paymentMethod: 'debit',
    kasirId: 'kasir1',
  },
  {
    id: 'TRX006',
    date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    items: [
      { product: MOCK_PRODUCTS[10], quantity: 5 },
      { product: MOCK_PRODUCTS[11], quantity: 2 },
    ],
    total: 21000,
    paymentMethod: 'qris',
    kasirId: 'kasir1',
  },
  {
    id: 'TRX007',
    date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    items: [
      { product: MOCK_PRODUCTS[0], quantity: 5 },
      { product: MOCK_PRODUCTS[6], quantity: 2 },
    ],
    total: 36000,
    paymentMethod: 'tunai',
    kasirId: 'kasir1',
  },
  {
    id: 'TRX008',
    date: new Date().toISOString(),
    items: [{ product: MOCK_PRODUCTS[4], quantity: 2 }],
    total: 12000,
    paymentMethod: 'debit',
    kasirId: 'kasir1',
  },
];
